/**
 * Centralized dependency injection tokens.
 * Keep all tsyringe registration/resolve keys in one place to avoid drift.
 */
export const DI_TOKENS = {
  repositories: {
    user: "UserRepository",
    class: "ClassRepository",
    assignment: "AssignmentRepository",
    enrollment: "EnrollmentRepository",
    submission: "SubmissionRepository",
    dashboardQuery: "DashboardQueryRepository",
    similarity: "SimilarityRepository",
    testCase: "TestCaseRepository",
    testResult: "TestResultRepository",
    gradebook: "GradebookRepository",
    module: "ModuleRepository",
    notification: "NotificationRepository",
  },
  adapters: {
    supabaseAuth: "SupabaseAuthAdapter",
  },
  services: {
    storage: "StorageService",
    assignment: "AssignmentService",
    auth: "AuthService",
    class: "ClassService",
    submission: "SubmissionService",
    studentDashboard: "StudentDashboardService",
    teacherDashboard: "TeacherDashboardService",
    plagiarism: "PlagiarismService",
    user: "UserService",
    gradebook: "GradebookService",
    latePenalty: "LatePenaltyService",
    email: "EmailService",
    notification: "NotificationService",
    codeTest: "CodeTestService",
    testCase: "TestCaseService",
    module: "ModuleService",
    adminUser: "AdminUserService",
    adminAnalytics: "AdminAnalyticsService",
    adminClass: "AdminClassService",
    adminEnrollment: "AdminEnrollmentService",
    plagiarismSubmissionFile: "PlagiarismSubmissionFileService",
    plagiarismPersistence: "PlagiarismPersistenceService",
    plagiarismAutoAnalysis: "PlagiarismAutoAnalysisService",
    similarityPenalty: "SimilarityPenaltyService",
    semanticSimilarityClient: "SemanticSimilarityClient",
    crossClassSimilarity: "CrossClassSimilarityService",
    diffFragmentExplanation: "DiffFragmentExplanationService",
    matchFragmentExplanation: "MatchFragmentExplanationService",
  },
} as const
