reviews:
  target_branches:
    - "development"
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: "Write a short, imperative PR title."
  finishing_touches:
    unit_tests:
      enabled: true
