// Re-export all auth types from shared layer for backward compatibility
export type {
  UserRole,
  User,
  LoginRequest,
  RegisterRequest,
  ForgotPasswordRequest,
  ResetPasswordRequest,
  ChangePasswordRequest,
  DeleteAccountRequest,
  AuthResponse,
  ForgotPasswordResponse,
  ResetPasswordResponse,
  ResetFlowResponse,
  ChangePasswordResponse,
  DeleteAccountResponse,
  ValidationError,
  ValidationResult,
  RegistrationStep,
  RegistrationStepInfo,
} from "@/shared/types/auth"
