-- Add new notification type enum values
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'ASSIGNMENT_UPDATED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'NEW_SUBMISSION_RECEIVED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'LATE_SUBMISSION_RECEIVED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SIMILARITY_DETECTED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'STUDENT_ENROLLED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'STUDENT_UNENROLLED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'NEW_USER_REGISTERED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'REMOVED_FROM_CLASS';
