export { plagiarismRoutes } from "@/modules/plagiarism/plagiarism.controller.js"
export { crossClassSimilarityRoutes } from "@/modules/plagiarism/cross-class-similarity.controller.js"
export { PlagiarismService } from "@/modules/plagiarism/plagiarism.service.js"
export { CrossClassSimilarityService } from "@/modules/plagiarism/cross-class-similarity.service.js"
export { PlagiarismAutoAnalysisService } from "@/modules/plagiarism/plagiarism-auto-analysis.service.js"
export { SimilarityRepository } from "@/modules/plagiarism/similarity.repository.js"
